Replace init script to fix systemd redirection
Work around #826214 and #826215 by using old skeleton boilerplate
instead of sourcing init-d-script.

diff --git a/debian/sidedoor.init b/debian/sidedoor.init
--- a/debian/sidedoor.init
+++ b/debian/sidedoor.init
@@ -1,8 +1,4 @@
 #!/bin/sh
-# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
-if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
-    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
-fi
 ### BEGIN INIT INFO
 # Provides:          sidedoor
 # Required-Start:    $remote_fs $syslog
@@ -12,8 +8,14 @@ fi
 # Short-Description: SSH connection daemon
 ### END INIT INFO
 
+# Do NOT "set -e"
+
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC='SSH connection daemon'
-DAEMON=/usr/bin/sidedoor
+NAME=sidedoor
+DAEMON="/usr/bin/$NAME"
+PIDFILE="/var/run/$NAME.pid"
 START_ARGS='--chuid sidedoor --background --make-pidfile'
 
 if [ -r /etc/default/sidedoor ]; then
@@ -23,5 +25,85 @@ fi
 
 do_stop_cmd() {
   start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 \
-    --pidfile "$PIDFILE" --name "$NAME" --remove-pidfile
+    --pidfile "$PIDFILE" --name "$NAME"
+  # Older versions of start-stop-daemon do not support --remove-pidfile
+  RETVAL="$?"
+  rm -f "$PIDFILE"
+  return "$RETVAL"
 }
+
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
+. /lib/lsb/init-functions
+
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+    # Return
+    #   0 if daemon has been started
+    #   1 if daemon was already running
+    #   2 if daemon could not be started
+    start-stop-daemon --start --quiet --pidfile "$PIDFILE" \
+        $START_ARGS \
+        --exec "$DAEMON" --test > /dev/null \
+        || return 1
+    start-stop-daemon --start --quiet --pidfile "$PIDFILE" \
+        $START_ARGS \
+        --exec "$DAEMON" -- $DAEMON_ARGS \
+        || return 2
+}
+
+case "$1" in
+  start)
+    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+    do_start
+    case "$?" in
+        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
+    ;;
+  stop)
+    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+    do_stop_cmd
+    case "$?" in
+        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
+    ;;
+  status)
+    status_of_proc "$DAEMON" "$NAME" && exit 0 || exit "$?"
+    ;;
+  restart|force-reload)
+    log_daemon_msg "Restarting $DESC" "$NAME"
+    do_stop_cmd
+    case "$?" in
+      0|1)
+        do_start
+        case "$?" in
+            0) log_end_msg 0 ;;
+            1) log_end_msg 1 ;; # Old process is still running
+            *) log_end_msg 1 ;; # Failed to start
+        esac
+        ;;
+      *)
+        # Failed to stop
+        log_end_msg 1
+        ;;
+    esac
+    ;;
+  *)
+    echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+    exit 3
+    ;;
+esac
+
+:
